### ISSUE TITLE
Dynamically change http status code

### ISSUE THREAD

**Issue by ezra-lieblich** [nicholasf/fakepoint#8]
Is there any way to change the status code on a fake endpoint after a certain amount of calls? I'm trying to write a test that monitors an endpoint for status code changes that repetitively gets the endpoint. 

Really love the plugin and is so much easier than go's http test package.

**Comment by nicholasf** [comment]
Thanks. I'll look into it for you.

**Comment by nicholasf** [comment]
Hey,

Sorry, but I've stopped working with golang. I'll update this project to indicate that.
